In [1]:
import pandas as pd
from sqlalchemy import create_engine
engine = create_engine(
    "postgresql+psycopg2://postgres:admin@localhost:5433/ecommerce_profitability"
)

In [2]:
query = "SELECT COUNT(*) AS total_customers FROM customers"

df = pd.read_sql(query, engine)

df

   total_customers
0            99441

In [3]:
orders = pd.read_sql(
    "SELECT * FROM orders",
    engine
)

orders.head()

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26

In [4]:
orders.shape

(99441, 8)

In [5]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [6]:
date_columns = [
    "order_purchase_timestamp",
    "order_approved_at",
    "order_delivered_carrier_date",
    "order_delivered_customer_date",
    "order_estimated_delivery_date"
]

for col in date_columns:
    orders[col] = pd.to_datetime(orders[col])

In [7]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99441 entries, 0 to 99440
Data columns (total 8 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       99441 non-null  object
 1   customer_id                    99441 non-null  object
 2   order_status                   99441 non-null  object
 3   order_purchase_timestamp       99441 non-null  datetime64[ns]
 4   order_approved_at              99281 non-null  datetime64[ns]
 5   order_delivered_carrier_date   97658 non-null  datetime64[ns]
 6   order_delivered_customer_date  96476 non-null  datetime64[ns]
 7   order_estimated_delivery_date  99441 non-null  datetime64[ns]
dtypes: datetime64[ns](5), object(3)
memory usage: 6.1+ MB

In [8]:
orders["is_late"] = (
    orders["order_delivered_customer_date"]
    > orders["order_estimated_delivery_date"]
).astype("boolean")

orders.loc[
    orders["order_delivered_customer_date"].isna(),
    "is_late"
] = pd.NA

In [9]:
orders["is_late"].value_counts()

is_late
False    88649
True      7827
Name: count, dtype: Int64

In [10]:
orders.loc[
    orders["order_delivered_customer_date"].isna(),
    "is_late"
] = pd.NA

In [11]:
orders = pd.read_sql("SELECT * FROM orders", engine)
order_items = pd.read_sql("SELECT * FROM order_items", engine)
products = pd.read_sql("SELECT * FROM products", engine)
sellers = pd.read_sql("SELECT * FROM sellers", engine)

In [12]:
sales = order_items.copy()

In [13]:
sales = sales.merge(
    orders[
        [
            "order_id",
            "customer_id",
            "order_status",
            "order_purchase_timestamp",
            "order_delivered_customer_date",
            "order_estimated_delivery_date"
        ]
    ],
    on="order_id",
    how="left"
)

In [14]:
sales = sales.merge(
    products[
        [
            "product_id",
            "product_category_name",
            "product_weight_g",
            "product_length_cm",
            "product_height_cm",
            "product_width_cm"
        ]
    ],
    on="product_id",
    how="left"
)

In [15]:
sales = sales.merge(
    sellers[
        [
            "seller_id",
            "seller_city",
            "seller_state"
        ]
    ],
    on="seller_id",
    how="left"
)

In [16]:
sales.shape

(112650, 19)

In [17]:
sales.head()

,order_id,order_item_id,product_id,seller_id,shipping_limit_date,price,freight_value,customer_id,order_status,order_purchase_timestamp,order_delivered_customer_date,order_estimated_delivery_date,product_category_name,product_weight_g,product_length_cm,product_height_cm,product_width_cm,seller_city,seller_state
0,00010242fe8c5a6d1ba2dd792cb16214,1,4244733e06e7ecb4970a6e2683c13e61,48436dade18ac8b2bce089ec2a041202,2017-09-19 09:45:35,58.90,13.29,3ce436f183e68e07877b285a838db11a,delivered,2017-09-13 08:59:02,2017-09-20 23:43:48,2017-09-29,cool_stuff,650.0,28.0,9.0,14.0,volta redonda,SP
1,00018f77f2f0320c557190d7a144bdd3,1,e5f2d52b802189ee658865ca93d83a8f,dd7ddc04e1b6c2c614352b383efe2d36,2017-05-03 11:05:13,239.90,19.93,f6dd3ec061db4e3987629fe6b26e5cce,delivered,2017-04-26 10:53:06,2017-05-12 16:04:24,2017-05-15,pet_shop,30000.0,50.0,30.0,40.0,sao paulo,SP
2,000229ec398224ef6ca0657da4fc703e,1,c777355d18b72b67abbeef9df44fd0fd,5b51032eddd242adc84c38acab88f23d,2018-01-18 14:48:30,199.00,17.87,6489ae5e4333f3693df5ad4372dab6d3,delivered,2018-01-14 14:33:31,2018-01-22 13:19:16,2018-02-05,moveis_decoracao,3050.0,33.0,13.0,33.0,borda da mata,MG
3,00024acbcdf0a6daa1e931b038114c75,1,7634da152a4610f1595efa32f14722fc,9d7a1d34a5052409006425275ba1c2b4,2018-08-15 10:10:18,12.99,12.79,d4eb9395c8c0431ee92fce09860c5a06,delivered,2018-08-08 10:00:35,2018-08-14 13:32:39,2018-08-20,perfumaria,200.0,16.0,10.0,15.0,franca,SP
4,00042b26cf59d7ce69dfabb4e55b4fd9,1,ac6c3623068f30de03045865e4e10089,df560393f3a51e74553ab94004ba5c87,2017-02-13 13:57:51,199.90,18.14,58dbd0b2d70206bf40e62cd34e84d795,delivered,2017-02-04 13:57:51,2017-03-01 16:42:31,2017-03-17,ferramentas_jardim,3750.0,35.0,40.0,30.0,loanda,PR

In [18]:
sales.columns.tolist()

['order_id',
 'order_item_id',
 'product_id',
 'seller_id',
 'shipping_limit_date',
 'price',
 'freight_value',
 'customer_id',
 'order_status',
 'order_purchase_timestamp',
 'order_delivered_customer_date',
 'order_estimated_delivery_date',
 'product_category_name',
 'product_weight_g',
 'product_length_cm',
 'product_height_cm',
 'product_width_cm',
 'seller_city',
 'seller_state']

In [19]:
sales[
    [
        "product_id",
        "product_category_name"
    ]
].isna().sum()

product_id                  0
product_category_name    1603
dtype: int64

In [20]:
sales[
    [
        "seller_id",
        "seller_city"
    ]
].isna().sum()

seller_id      0
seller_city    0
dtype: int64

In [21]:
sales["revenue"] = sales["price"]

In [22]:
sales["estimated_product_cost"] = sales["revenue"] * 0.65

In [23]:
sales["estimated_contribution"] = (
    sales["revenue"]
    - sales["estimated_product_cost"]
    - sales["freight_value"]
)

In [24]:
sales["contribution_margin"] = (
    sales["estimated_contribution"]
    / sales["revenue"]
)

In [25]:
sales["contribution_margin"] = (
    sales["contribution_margin"]
    .replace([float("inf"), -float("inf")], pd.NA)
)

In [26]:
sales["delivery_days"] = (
    pd.to_datetime(sales["order_delivered_customer_date"])
    - pd.to_datetime(sales["order_purchase_timestamp"])
).dt.days

In [27]:
sales["contribution_margin"] = (
    sales["contribution_margin"]
    .replace([float("inf"), -float("inf")], pd.NA)
)

In [28]:
sales["delivery_days"] = (
    pd.to_datetime(sales["order_delivered_customer_date"])
    - pd.to_datetime(sales["order_purchase_timestamp"])
).dt.days

In [29]:
sales["is_late"] = (
    pd.to_datetime(sales["order_delivered_customer_date"])
    > pd.to_datetime(sales["order_estimated_delivery_date"])
).astype("boolean")

sales.loc[
    sales["order_delivered_customer_date"].isna(),
    "is_late"
] = pd.NA

In [30]:
sales.to_csv(
    "../data/cleaned/sales_cleaned.csv",
    index=False
)